version: '3.8'

services:
  news-agent:
    build: .
    container_name: news-agent-web
    ports:
      - "8080:8080"
    environment:
      # MongoDB - usa quello locale di default
      - MONGO_URI=${MONGODB_URI:-mongodb://host.docker.internal:27017/news_agent_web}
      # Ollama - usa quello locale di default  
      - OLLAMA_URL=${OLLAMA_URL:-http://host.docker.internal:11434}
      # API Keys (opzionali)
      - SCRAPINGDOG_API_KEY=${SCRAPINGDOG_API_KEY:-}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      # Mount dei log (opzionale)
      - ./logs:/app/logs
    restart: unless-stopped
    depends_on:
      - mongodb
    profiles:
      - full

  # MongoDB opzionale - decommenta se non hai MongoDB locale
  mongodb:
    image: mongo:7-jammy
    container_name: news-agent-mongodb
    ports:
      - "27017:27017"
    volumes:
      # Dati persistenti locali
      - ./data/mongodb:/data/db
    environment:
      - MONGO_INITDB_DATABASE=news_agent
    restart: unless-stopped
    profiles:
      - full
      - mongodb-only

  # Servizio solo per l'app (usa MongoDB e Ollama esterni)
  news-agent-standalone:
    build: .
    container_name: news-agent-web-standalone
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=${MONGODB_URI:-mongodb://host.docker.internal:27017/news_agent_web}
      - OLLAMA_URL=${OLLAMA_URL:-http://host.docker.internal:11434}
      - SCRAPINGDOG_API_KEY=${SCRAPINGDOG_API_KEY:-}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped